version: '3.8'

services:
  # PHP/Laravel アプリケーション
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: attendance_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - attendance_network
    depends_on:
      - db

  # Nginx ウェブサーバー
  nginx:
    image: nginx:alpine
    container_name: attendance_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - attendance_network
    depends_on:
      - app

  # MySQL データベース
  db:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - attendance_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: attendance_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "8081:80"
    networks:
      - attendance_network
    depends_on:
      - db

networks:
  attendance_network:
    driver: bridge

volumes:
  mysql_data:
